# Generated by Django 5.0.6 on 2024-08-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examportal', '0002_question_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=1),
        ),
    ]
