# Generated by Django 5.0.6 on 2024-07-30 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('admission_number', models.IntegerField(null=True, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('enrolled_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultapp.class')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_scores', models.IntegerField(blank=True)),
                ('exam_scores', models.IntegerField(blank=True)),
                ('total_scores', models.IntegerField(blank=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultapp.student')),
                ('subject', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='examportal.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('assigned_class', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultapp.class')),
            ],
        ),
    ]
