# Generated by Django 5.0.6 on 2024-08-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultapp', '0005_alter_student_result_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
